(function () {
  "use strict";

  const core = (window.MZHudCore = window.MZHudCore || {});

  const selectOptions = {
    hudPosition: [
      "bottom-left",
      "bottom-center",
      "bottom-right",
      "center-left",
      "center",
      "center-right",
      "top-left",
      "top-center",
      "top-right",
    ],
    minimapStyle: ["circle", "square", "default"],
    minimapVisibility: ["always", "vehicle", "foot", "never"],
    speedometerPosition: [
      "bottom-left",
      "bottom-center",
      "bottom-right",
      "center-left",
      "center",
      "center-right",
      "top-left",
      "top-center",
      "top-right",
    ],
    unit: ["kmh", "mph"],
    speedometerStyle: [
      "digital",
      "analog",
      "minimal",
      "racing",
      "classic",
      "apex",
      "vector",
    ],
    logoPosition: [
      "bottom-left",
      "bottom-center",
      "bottom-right",
      "center-left",
      "center",
      "center-right",
      "top-left",
      "top-center",
      "top-right",
    ],
    chatPreset: [
      "left-top",
      "left-center",
      "left-bottom",
      "center-top",
      "center",
      "center-bottom",
      "right-top",
      "right-center",
      "right-bottom",
    ],
    icon: [
      "heart",
      "shield",
      "utensils",
      "droplet",
      "zap",
      "wind",
      "brain",
      "mic",
      "radio",
    ],
    elementStyle: ["circle", "bar", "square", "pill", "apex"],
    itemPosition: [
      "bottom-left",
      "bottom-center",
      "bottom-right",
      "center-left",
      "center",
      "center-right",
      "top-left",
      "top-center",
      "top-right",
    ],
  };

  const labels = {
    "bottom-left": "Esquerda inferior",
    "bottom-center": "Centro inferior",
    "bottom-right": "Direita inferior",
    "center-left": "Esquerda centro",
    center: "Centro",
    "center-right": "Direita centro",
    "top-left": "Esquerda superior",
    "top-center": "Centro superior",
    "top-right": "Direita superior",
    "left-top": "Esquerda superior",
    "left-center": "Esquerda centro",
    "left-bottom": "Esquerda inferior",
    "center-top": "Centro superior",
    "center-bottom": "Centro inferior",
    "right-top": "Direita superior",
    "right-center": "Direita centro",
    "right-bottom": "Direita inferior",
    circle: "Círculo",
    bar: "Barra",
    square: "Quadrado",
    pill: "Pílula",
    default: "Padrão",
    always: "Sempre ativo",
    vehicle: "Só no carro",
    foot: "Só a pé",
    never: "Nunca",
    kmh: "KM/H",
    mph: "MPH",
    digital: "Digital",
    analog: "Analógico",
    minimal: "Minimalista",
    racing: "Racing",
    classic: "Clássico",
    apex: "Apex",
    vector: "Vector",
  };

  const colorPresets = [
    "#ef4444",
    "#f97316",
    "#eab308",
    "#22c55e",
    "#06b6d4",
    "#3b82f6",
    "#8b5cf6",
    "#ec4899",
    "#ffffff",
  ];

  const speedometerThemes = {
    blue: {
      primary_color: "#ffffff",
      secondary_color: "#3b82f6",
      accent_color: "#ef4444",
      background_color: "#000000",
    },
    red: {
      primary_color: "#ffffff",
      secondary_color: "#ef4444",
      accent_color: "#f97316",
      background_color: "#080808",
    },
    green: {
      primary_color: "#ffffff",
      secondary_color: "#22c55e",
      accent_color: "#eab308",
      background_color: "#020617",
    },
    purple: {
      primary_color: "#ffffff",
      secondary_color: "#8b5cf6",
      accent_color: "#ec4899",
      background_color: "#050314",
    },
    orange: {
      primary_color: "#ffffff",
      secondary_color: "#f97316",
      accent_color: "#ef4444",
      background_color: "#090604",
    },
    mono: {
      primary_color: "#f8fafc",
      secondary_color: "#94a3b8",
      accent_color: "#ffffff",
      background_color: "#000000",
    },
  };

  Object.assign(core, {
    selectOptions,
    labels,
    colorPresets,
    speedometerThemes,
  });
})();
